#!/bin/bash

# Delay before starting
DELAY=5

OUTPUT_DIR=$HOME/Pictures/gif
OUTPUT_FILE=`date +%Y-%m-%d_%H:%M:%S`.gif
OUTPUT_PATH=$OUTPUT_DIR/$OUTPUT_FILE


# Duration and output file
if [ $# -gt 0 ]; then
    D="--duration=$@"
else
    if [ ! -d $OUTPUT_PATH ]; then
        mkdir -p $OUTPUT_DIR
    else
        if [ -f $OUTPUT_PATH ]; then
            rm $OUTPUT_PATH
        fi
    fi
    echo Default recording duration 5s to $OUTPUT_PATH
    D="--duration=5 $OUTPUT_PATH"
fi

# xrectsel from https://github.com/lolilolicon/xrectsel
ARGUMENTS=$(xrectsel "--x=%x --y=%y --width=%w --height=%h") || exit -1

echo Delaying $DELAY seconds. After that, byzanz will start
for (( i=$DELAY; i>0; --i )) ; do
    echo $i
    sleep 1
done

# byzanz-record --verbose --delay=0 ${ARGUMENTS} $D
byzanz-record --duration=50 --delay=0 ${ARGUMENTS} $OUTPUT_PATH

