#!/bin/bash

# Delay before starting
DELAY=5


# Duration and output file
if [ $# -gt 0 ]; then
    D="--duration=$@"
else
    if [ ! -d ~/tmp/gif ]; then
        mkdir -p ~/tmp/gif
    else
        if [ -f ~/tmp/gif/recorded.gif ]; then
            rm ~/tmp/gif/recorded.gif
        fi
    fi
    echo Default recording duration 5s to ~/tmp/gif/recorded.gif
    D="--duration=5 ~/tmp/gif/recorded.gif"
fi

# xrectsel from https://github.com/lolilolicon/xrectsel
ARGUMENTS=$(xrectsel "--x=%x --y=%y --width=%w --height=%h") || exit -1

echo Delaying $DELAY seconds. After that, byzanz will start
for (( i=$DELAY; i>0; --i )) ; do
    echo $i
    sleep 1
done

# byzanz-record --verbose --delay=0 ${ARGUMENTS} $D
byzanz-record --duration=50 --delay=0 ${ARGUMENTS} ~/tmp/gif/recorded.gif

