#!/usr/bin/env bash
ROFI_SELECTION=$(find $HOME/workspace -maxdepth 6 -name ".idea"  -not -path "*/node_modules/*" | sed 's/\.idea//g' | sed "s#$HOME/##g" | rofi -dmenu -p "storm-modi > ")

[[ ${ROFI_SELECTION} != "" ]] && eval '$HOME/.bin/phpstorm $HOME/${ROFI_SELECTION}'
