#!/usr/bin/env bash
ROFI_SELECTION=$(find $HOME/workspace -maxdepth 6 -name ".idea"  -not -path "*/node_modules/*" | sed 's/\.idea//g' | sed "s#$HOME/##g" | rofi -dmenu -p "storm-modi > ")

WEBSTORM_PATH="${WEBSTORM_PATH:-$(which webstorm)}"
PHPSTORM_PATH="${PHPSTORM_PATH:-$(which phpstorm)}"

_selectStormPath() {
  if [[ -e "${HOME}/${1}/.idea/php.xml" ]]; then
    echo "$PHPSTORM_PATH"
    exit;
  fi
  echo "$WEBSTORM_PATH"
}

_main() {
   if [[ -n ${ROFI_SELECTION} ]]; then
      echo "Selected: ${ROFI_SELECTION}"

      local stormPath=$(_selectStormPath "$ROFI_SELECTION")
      echo "Using: $stormPath"
	    eval '$stormPath $HOME/${ROFI_SELECTION}'
  fi
}

_main
