#
# .zshrc config
#
# basic vim, golang, nvm, setup
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Grab antigen our zsh package manager
source /home/dduncan/antigen/antigen.zsh

if [[ -e "${HOME}/.aliases" ]]; then
  source "${HOME}/.aliases"
fi

# gruvbox color theme
#source ~/gruvbox/gruvbox_256palette.sh
source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh"

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme agnoster

# Tell antigen that you're done.
antigen apply

#powerline?
export POWERLINE_CONFIG_COMMAND=/home/dduncan/.local/bin/powerline-config 

# nvm
export NVM_DIR="/home/dduncan/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# add our personal bin to path
PATH=$HOME/.bin/:$PATH

# add composer to path
PATH=$PATH:~/.config/composer/vendor/bin/

#golang
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go

# add yarn to bin
PATH=$PATH:`yarn global bin`

# configure editors
export VISUAL=vim
export EDITOR="$VISUAL"

# easy browser sync
alias bs="browser-sync start --proxy 'localhost:4200' --files 'dist/*'"

# k8s aliases, move these to ~/.aliases
alias kctl="kubectl"
alias kpods="kctl get pods"
alias klogs="kctl logs -f"
alias kexec="kctl exec -it"

# k8s completion
if [ $commands[kubectl] ]; then
    source <(kubectl completion zsh)
fi

# tabtab source for electron-forge package
# uninstall by removing these lines or running `tabtab uninstall electron-forge`
[[ -f /home/dduncan/.config/yarn/global/node_modules/tabtab/.completions/electron-forge.zsh ]] && . /home/dduncan/.config/yarn/global/node_modules/tabtab/.completions/electron-forge.zsh

# work variables
source ~/.intellifarms

