#!/usr/bin/env bash
# Bootstrap for when we clone/update dotfiles

# check to see if we have vundle installed
if [[ ! -e $HOME/.vim/bundle ]]; then
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

# check to make sure we have plugins installed
vim +PluginInstall +qall

read -p "Do you want to run a full bootstrap install? [Y/N] " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]
then
    . $HOME/bootstrap.sh
fi
